# Generated by Django 5.1.4 on 2025-02-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
